name: 'Publish to PyPI'
description: 'Publish an python package using the setuptools build system'
inputs:
  working-directory:
    description: "Path within the repo to the folder where the myproject.toml file lives"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Install Python package dependencies
      run: |
        python -m pip install -U pip setuptools wheel twine build
        pip install -e .
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Build dist
      run: python -m build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Check dist
      run: twine check dist/*
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
          packages-dir: ${{ inputs.working-directory }}/dist/
          skip-existing: true
