name: 'Publish to PyPI'
description: 'Publish an python package using the poetry build system'
inputs:
  working-directory:
    description: "Path within the repo to the folder where the myproject.toml file lives"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with: 
        version: 1.6.1
    - name: Install dependencies
      run: poetry install
      working-directory: ${{ inputs.working-directory }}
    - name: Build
      run: poetry build
      working-directory: ${{ inputs.working-directory }}
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
          packages-dir: ${{ inputs.working-directory }}/dist/
          skip-existing: true
